title: "rafaelldi blog"
url: "https://rafaelldi.github.io"
repository: "rafaelldi/rafaelldi.github.io"
minimal_mistakes_skin: default
search: true
locale: "en-US"
logo: "/assets/images/logo.png"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "MDEwOlJlcG9zaXRvcnkyODU4Mzg4NjE="
    category_name        : "Announcements"
    category_id          : "MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMzMDQwMjc0"
    discussion_term      : "title"
    reactions_enabled    : '1'
    theme                : "light"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 10
paginate_path: /page:num/
timezone: Europe/Berlin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      show_date: true
      comments: true
      toc: true
      toc_sticky: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
