title: "rafaelldi blog"
name: "Rival Abdrakhmanov"
email:
url: "https://rafaelldi.github.io"
repository: "rafaelldi/rafaelldi.github.io"
description: >- # this means to ignore newlines until "baseurl:"
  Hello and Welcome! My name is Rival, and I'm a .NET developer. In this blog, I describe my development experience and explore exciting technologies. I hope you'll find it useful.
minimal_mistakes_skin: default
search: true
locale: "en-US"
logo: "/assets/images/logo.png"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "MDEwOlJlcG9zaXRvcnkyODU4Mzg4NjE="
    category_name        : "Announcements"
    category_id          : "MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMzMDQwMjc0"
    discussion_term      : "title"
    reactions_enabled    : '1'
    theme                : "light"

social:
  type: Person
  name: Rival Abdrakhmanov
  links:
    - "https://github.com/rafaelldi"
    - "https://dotnet.social/@rafaelldi"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
timezone: Europe/Moscow

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Rival Abdrakhmanov"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Hello and Welcome! My name is Rival, and I'm a .NET developer. In this blog, I describe my development experience and explore exciting technologies. I hope you'll find it useful."
  location: "Munich, Germany"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rafaelldi"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://dotnet.social/@rafaelldi"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rafaelldi"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://dotnet.social/@rafaelldi"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      show_date: true
      comments: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
